name: Generate Doc
on: [push]
  jobs:
    deploy:
      steps:
        - name: Doxygen Action
          uses: mattnotmitt/doxygen-action@1.9.1
          with:
            working-directory: 'docs/doxygen'