name: Generate Doc
on: [push]
jobs:
  deployss:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - run: ls ../ -la
      - run: pwd
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.1
        with:
         working-directory: 'docs/doxygen'
