name: Generate Doc
on: [push]
jobs:
  deploys:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ''
          
      - run: ls -la
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.1
      - run: ls -la
